// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6LG7aL2E1CQLS8Y1w8JW8rc3-w0MM1uc',
    appId: '1:856093413898:web:fb8801670d1c0a4e2205f3',
    messagingSenderId: '856093413898',
    projectId: 'final-year-project-12072',
    authDomain: 'final-year-project-12072.firebaseapp.com',
    storageBucket: 'final-year-project-12072.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQYMjs-kKlAjf2uDpNn2tjA3-LBn8ak-c',
    appId: '1:856093413898:android:cebcbbdef4fe307d2205f3',
    messagingSenderId: '856093413898',
    projectId: 'final-year-project-12072',
    storageBucket: 'final-year-project-12072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT0pjfBRoCgNRcEp5LejbjP0qBQb9pfz8',
    appId: '1:856093413898:ios:465defb1119f70142205f3',
    messagingSenderId: '856093413898',
    projectId: 'final-year-project-12072',
    storageBucket: 'final-year-project-12072.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT0pjfBRoCgNRcEp5LejbjP0qBQb9pfz8',
    appId: '1:856093413898:ios:465defb1119f70142205f3',
    messagingSenderId: '856093413898',
    projectId: 'final-year-project-12072',
    storageBucket: 'final-year-project-12072.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6LG7aL2E1CQLS8Y1w8JW8rc3-w0MM1uc',
    appId: '1:856093413898:web:643d66c243aee1a02205f3',
    messagingSenderId: '856093413898',
    projectId: 'final-year-project-12072',
    authDomain: 'final-year-project-12072.firebaseapp.com',
    storageBucket: 'final-year-project-12072.firebasestorage.app',
  );
}
