name: trusttrack
description: TrustTrack final year project
publish_to: 'none'
version: 1.0.0+1

# Environment settings
environment:
  sdk: ">=3.3.0 <4.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.4

  http: ^1.2.2
  url_launcher: ^6.3.2

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.14.4

# Flutter configuration
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

# App icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"